[2023-05-18T08:43:33.261+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:871: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti: TaskInstance | None = qry.with_for_update().one_or_none()

[2023-05-18T08:43:33.310+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: read_cosmosdb_to_dataframe.read_cosmosdb manual__2023-05-18T08:43:30.262768+00:00 [queued]>
[2023-05-18T08:43:33.353+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: read_cosmosdb_to_dataframe.read_cosmosdb manual__2023-05-18T08:43:30.262768+00:00 [queued]>
[2023-05-18T08:43:33.354+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-18T08:43:33.354+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-05-18T08:43:33.355+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-18T08:43:33.424+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): read_cosmosdb> on 2023-05-18 08:43:30.262768+00:00
[2023-05-18T08:43:33.441+0000] {standard_task_runner.py:54} INFO - Started process 445 to run task
[2023-05-18T08:43:33.454+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'read_cosmosdb_to_dataframe', 'read_cosmosdb', 'manual__2023-05-18T08:43:30.262768+00:00', '--job-id', '3963', '--raw', '--subdir', 'DAGS_FOLDER/azure_cosmos.py', '--cfg-path', '/tmp/tmp5ccgij4k']
[2023-05-18T08:43:33.456+0000] {standard_task_runner.py:83} INFO - Job 3963: Subtask read_cosmosdb
[2023-05-18T08:43:33.458+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/azure_cosmos.py
[2023-05-18T08:43:34.707+0000] {task_command.py:384} INFO - Running <TaskInstance: read_cosmosdb_to_dataframe.read_cosmosdb manual__2023-05-18T08:43:30.262768+00:00 [running]> on host e2b22a48b078
[2023-05-18T08:43:34.715+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-18T08:43:35.159+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=read_cosmosdb_to_dataframe
AIRFLOW_CTX_TASK_ID=read_cosmosdb
AIRFLOW_CTX_EXECUTION_DATE=2023-05-18T08:43:30.262768+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-18T08:43:30.262768+00:00
[2023-05-18T08:43:35.161+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/azure_cosmos.py", line 7, in read_cosmosdb_to_dataframe
    client = cosmos_client.from_connection_string(conn_id)
AttributeError: module 'azure.cosmos.cosmos_client' has no attribute 'from_connection_string'
[2023-05-18T08:43:35.211+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=read_cosmosdb_to_dataframe, task_id=read_cosmosdb, execution_date=20230518T084330, start_date=20230518T084333, end_date=20230518T084335
[2023-05-18T08:43:35.284+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3963 for task read_cosmosdb (module 'azure.cosmos.cosmos_client' has no attribute 'from_connection_string'; 445)
[2023-05-18T08:43:35.341+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-05-18T08:43:35.430+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
