[2023-05-11T17:39:45.336+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:871: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti: TaskInstance | None = qry.with_for_update().one_or_none()

[2023-05-11T17:39:45.381+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spark_process_data_14.spark_job_clean_data_by_ssh scheduled__2023-05-10T17:00:00+00:00 [queued]>
[2023-05-11T17:39:45.414+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spark_process_data_14.spark_job_clean_data_by_ssh scheduled__2023-05-10T17:00:00+00:00 [queued]>
[2023-05-11T17:39:45.414+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-11T17:39:45.415+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-05-11T17:39:45.415+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-11T17:39:45.469+0000] {taskinstance.py:1383} INFO - Executing <Task(SSHOperator): spark_job_clean_data_by_ssh> on 2023-05-10 17:00:00+00:00
[2023-05-11T17:39:45.480+0000] {standard_task_runner.py:54} INFO - Started process 59 to run task
[2023-05-11T17:39:45.490+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'spark_process_data_14', 'spark_job_clean_data_by_ssh', 'scheduled__2023-05-10T17:00:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/spark_process_scheduler.py', '--cfg-path', '/tmp/tmp2qrfmpdc']
[2023-05-11T17:39:45.492+0000] {standard_task_runner.py:83} INFO - Job 119: Subtask spark_job_clean_data_by_ssh
[2023-05-11T17:39:45.494+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/spark_process_scheduler.py
[2023-05-11T17:39:45.803+0000] {task_command.py:384} INFO - Running <TaskInstance: spark_process_data_14.spark_job_clean_data_by_ssh scheduled__2023-05-10T17:00:00+00:00 [running]> on host 09877495cfa0
[2023-05-11T17:39:45.819+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-11T17:39:46.133+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=pioneer22022001@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_process_data_14
AIRFLOW_CTX_TASK_ID=spark_job_clean_data_by_ssh
AIRFLOW_CTX_EXECUTION_DATE=2023-05-10T17:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-10T17:00:00+00:00
[2023-05-11T17:39:46.135+0000] {ssh.py:135} INFO - Creating ssh_client
[2023-05-11T17:39:46.268+0000] {ssh.py:112} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2023-05-11T17:39:46.311+0000] {base.py:71} INFO - Using connection ID 'ssh_connection_spark' for task execution.
[2023-05-11T17:39:46.313+0000] {ssh.py:299} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2023-05-11T17:39:49.389+0000] {ssh.py:341} INFO - Failed to connect. Sleeping before retry attempt 1
[2023-05-11T17:39:50.627+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-11T17:39:56.969+0000] {ssh.py:341} INFO - Failed to connect. Sleeping before retry attempt 2
[2023-05-11T17:40:04.937+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 172, in execute
    with self.get_ssh_client() as ssh_client:
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 136, in get_ssh_client
    return self.get_hook().get_conn()
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/ssh/hooks/ssh.py", line 348, in get_conn
    before_sleep=log_before_sleep,
  File "/usr/local/lib/python3.7/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.7/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/usr/local/lib/python3.7/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/ssh/hooks/ssh.py", line 351, in get_conn
    client.connect(**connect_kwargs)
  File "/usr/local/lib/python3.7/site-packages/paramiko/client.py", line 388, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 172.27.0.9
[2023-05-11T17:40:04.998+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-11T17:40:05.028+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_process_data_14, task_id=spark_job_clean_data_by_ssh, execution_date=20230510T170000, start_date=20230511T173945, end_date=20230511T174005
[2023-05-11T17:40:05.115+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 119 for task spark_job_clean_data_by_ssh ([Errno None] Unable to connect to port 22 on 172.27.0.9; 59)
[2023-05-11T17:40:05.226+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-05-11T17:40:05.406+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
