[2023-05-18T09:05:07.656+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:871: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti: TaskInstance | None = qry.with_for_update().one_or_none()

[2023-05-18T09:05:07.730+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: read_cosmosdb_to_dataframe.read_cosmosdb manual__2023-05-18T09:05:04.895314+00:00 [queued]>
[2023-05-18T09:05:07.771+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: read_cosmosdb_to_dataframe.read_cosmosdb manual__2023-05-18T09:05:04.895314+00:00 [queued]>
[2023-05-18T09:05:07.771+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-18T09:05:07.772+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-05-18T09:05:07.773+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-18T09:05:07.844+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): read_cosmosdb> on 2023-05-18 09:05:04.895314+00:00
[2023-05-18T09:05:07.858+0000] {standard_task_runner.py:54} INFO - Started process 551 to run task
[2023-05-18T09:05:07.871+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'read_cosmosdb_to_dataframe', 'read_cosmosdb', 'manual__2023-05-18T09:05:04.895314+00:00', '--job-id', '3966', '--raw', '--subdir', 'DAGS_FOLDER/azure_cosmos.py', '--cfg-path', '/tmp/tmpzll94517']
[2023-05-18T09:05:07.873+0000] {standard_task_runner.py:83} INFO - Job 3966: Subtask read_cosmosdb
[2023-05-18T09:05:07.875+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/azure_cosmos.py
[2023-05-18T09:05:09.195+0000] {task_command.py:384} INFO - Running <TaskInstance: read_cosmosdb_to_dataframe.read_cosmosdb manual__2023-05-18T09:05:04.895314+00:00 [running]> on host 52f64dcd5110
[2023-05-18T09:05:09.207+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-18T09:05:09.808+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=read_cosmosdb_to_dataframe
AIRFLOW_CTX_TASK_ID=read_cosmosdb
AIRFLOW_CTX_EXECUTION_DATE=2023-05-18T09:05:04.895314+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-18T09:05:04.895314+00:00
[2023-05-18T09:05:09.830+0000] {_universal.py:513} INFO - Request URL: 'https://tranvietcuonghust.documents.azure.com:443/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'CosmosDBPythonQuickstart'
No body was attached to the request
[2023-05-18T09:05:10.269+0000] {_universal.py:549} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json'
    'Content-Location': 'REDACTED'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-max-media-storage-usage-mb': 'REDACTED'
    'x-ms-media-storage-usage-mb': 'REDACTED'
    'x-ms-databaseaccount-consumed-mb': 'REDACTED'
    'x-ms-databaseaccount-reserved-mb': 'REDACTED'
    'x-ms-databaseaccount-provisioned-mb': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-gatewayversion': 'REDACTED'
    'Date': 'Thu, 18 May 2023 09:05:09 GMT'
[2023-05-18T09:05:10.270+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/azure_cosmos.py", line 10, in read_cosmosdb_to_dataframe
    container = client.get_database(database_name).get_container(container_name)
AttributeError: 'CosmosClient' object has no attribute 'get_database'
[2023-05-18T09:05:10.310+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=read_cosmosdb_to_dataframe, task_id=read_cosmosdb, execution_date=20230518T090504, start_date=20230518T090507, end_date=20230518T090510
[2023-05-18T09:05:10.362+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3966 for task read_cosmosdb ('CosmosClient' object has no attribute 'get_database'; 551)
[2023-05-18T09:05:10.435+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-05-18T09:05:10.526+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
