[2023-05-11T17:52:27.199+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:871: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti: TaskInstance | None = qry.with_for_update().one_or_none()

[2023-05-11T17:52:27.277+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: job_1_tranvietcuong.send_email manual__2023-05-11T17:52:19.505720+00:00 [queued]>
[2023-05-11T17:52:27.334+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: job_1_tranvietcuong.send_email manual__2023-05-11T17:52:19.505720+00:00 [queued]>
[2023-05-11T17:52:27.335+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-11T17:52:27.336+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-05-11T17:52:27.336+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-11T17:52:27.405+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): send_email> on 2023-05-11 17:52:19.505720+00:00
[2023-05-11T17:52:27.419+0000] {standard_task_runner.py:54} INFO - Started process 672 to run task
[2023-05-11T17:52:27.429+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'job_1_tranvietcuong', 'send_email', 'manual__2023-05-11T17:52:19.505720+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/tranvietcuong.py', '--cfg-path', '/tmp/tmpjispziq6']
[2023-05-11T17:52:27.431+0000] {standard_task_runner.py:83} INFO - Job 190: Subtask send_email
[2023-05-11T17:52:27.434+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/tranvietcuong.py
[2023-05-11T17:52:27.681+0000] {task_command.py:384} INFO - Running <TaskInstance: job_1_tranvietcuong.send_email manual__2023-05-11T17:52:19.505720+00:00 [running]> on host 09877495cfa0
[2023-05-11T17:52:27.692+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-11T17:52:28.102+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=job_1_tranvietcuong
AIRFLOW_CTX_TASK_ID=send_email
AIRFLOW_CTX_EXECUTION_DATE=2023-05-11T17:52:19.505720+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-11T17:52:19.505720+00:00
[2023-05-11T17:52:28.327+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/utils/email.py:120: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-05-11T17:52:28.329+0000] {configuration.py:569} WARNING - section/key [smtp/smtp_user] not found in config
[2023-05-11T17:52:28.330+0000] {email.py:229} INFO - Email alerting: attempt 1
[2023-05-11T17:52:28.333+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tranvietcuong.py", line 43, in send_success_email
    email_operator.execute(context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/email.py", line 87, in execute
    custom_headers=self.custom_headers,
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 72, in send_email
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-05-11T17:52:28.394+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=job_1_tranvietcuong, task_id=send_email, execution_date=20230511T175219, start_date=20230511T175227, end_date=20230511T175228
[2023-05-11T17:52:28.461+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 190 for task send_email ([Errno 99] Cannot assign requested address; 672)
[2023-05-11T17:52:28.493+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-05-11T17:52:28.642+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
