[2023-05-11T17:45:16.761+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:871: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti: TaskInstance | None = qry.with_for_update().one_or_none()

[2023-05-11T17:45:16.806+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: job_1_tranvietcuong.file_process scheduled__2023-05-11T17:30:00+00:00 [queued]>
[2023-05-11T17:45:16.849+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: job_1_tranvietcuong.file_process scheduled__2023-05-11T17:30:00+00:00 [queued]>
[2023-05-11T17:45:16.850+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-11T17:45:16.850+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-05-11T17:45:16.851+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-11T17:45:16.930+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): file_process> on 2023-05-11 17:30:00+00:00
[2023-05-11T17:45:16.954+0000] {standard_task_runner.py:54} INFO - Started process 350 to run task
[2023-05-11T17:45:16.968+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'job_1_tranvietcuong', 'file_process', 'scheduled__2023-05-11T17:30:00+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/tranvietcuong.py', '--cfg-path', '/tmp/tmpf0k3vu5j']
[2023-05-11T17:45:16.971+0000] {standard_task_runner.py:83} INFO - Job 166: Subtask file_process
[2023-05-11T17:45:16.979+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/tranvietcuong.py
[2023-05-11T17:45:17.263+0000] {task_command.py:384} INFO - Running <TaskInstance: job_1_tranvietcuong.file_process scheduled__2023-05-11T17:30:00+00:00 [running]> on host 09877495cfa0
[2023-05-11T17:45:17.274+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-11T17:45:17.530+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=job_1_tranvietcuong
AIRFLOW_CTX_TASK_ID=file_process
AIRFLOW_CTX_EXECUTION_DATE=2023-05-11T17:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-11T17:30:00+00:00
[2023-05-11T17:45:17.532+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tranvietcuong.py", line 11, in file_process
    for file in os.listdir('opt/airflow/dags/tmp'):
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/tmp'
[2023-05-11T17:45:17.549+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-11T17:45:17.569+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=job_1_tranvietcuong, task_id=file_process, execution_date=20230511T173000, start_date=20230511T174516, end_date=20230511T174517
[2023-05-11T17:45:17.612+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 166 for task file_process ([Errno 2] No such file or directory: 'opt/airflow/dags/tmp'; 350)
[2023-05-11T17:45:17.634+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-05-11T17:45:17.954+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
